"""add policy table

Revision ID: 4bcbb338880d
Revises: 29d1749d8870
Create Date: 2025-06-22 14:04:10.564914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcbb338880d'
down_revision: Union[str, None] = '29d1749d8870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'policies',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('scheme_id', sa.String(), sa.ForeignKey('schemes.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('customer_id', sa.String(), sa.ForeignKey('customers.id', ondelete='CASCADE'), nullable=False),
        sa.Column('premium_amount', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('expiry_date', sa.Date(), nullable=False),
        sa.Column('agent_id', sa.String(), sa.ForeignKey('agents.id', ondelete='CASCADE'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
