"""remove commission rule from scheme

Revision ID: 8b27d389737b
Revises: f9f551e27ea6
Create Date: 2025-06-24 00:22:31.675953

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b27d389737b"
down_revision: Union[str, Sequence[str], None] = "f9f551e27ea6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commissions",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("txn_id", sa.String(length=20), nullable=False),
        sa.Column("commission_amt", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["txn_id"], ["transactions.transaction_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("txn_id"),
    )
    op.create_unique_constraint(None, "admins", ["id"])
    op.execute(
        "ALTER TABLE employees ALTER COLUMN dept TYPE departmentenum USING dept::departmentenum"
    )
    op.create_unique_constraint(None, "plans", ["id"])
    op.drop_column("schemes", "commission_rule")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schemes",
        sa.Column(
            "commission_rule",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "plans", type_="unique")
    op.alter_column(
        "employees",
        "dept",
        existing_type=sa.Enum(
            "OPERATIONS", "HR", "FINANCE", "TECH", name="departmentenum"
        ),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.drop_constraint(None, "admins", type_="unique")
    op.drop_table("commissions")
    # ### end Alembic commands ###
