"""create transaction table

Revision ID: bacbe695dc88
Revises: 5ceb0f6009bb
Create Date: 2025-06-23 09:56:23.322131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.utils.transaction_enum import TransactionStatus, TransactionType


# revision identifiers, used by Alembic.
revision: str = 'bacbe695dc88'
down_revision: Union[str, None] = '5ceb0f6009bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transactions',
        sa.Column('transaction_id', sa.String(), primary_key=True),
        sa.Column('policy_id', sa.String(), sa.ForeignKey('policies.id', ondelete='CASCADE'), nullable=False),
        sa.Column('type', sa.Enum(TransactionType, name='transactiontype'), nullable=False),
        sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE')),
        sa.Column('status', sa.Enum(TransactionStatus, name='transactionstatus'), server_default=TransactionStatus.pending.value),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
